### ISSUE TITLE
Not able to Load played save files

### ISSUE THREAD

**Issue by Bluurix** [gibbed/Gibbed.Borderlands2#10]
Hello, I'm using the latest version of the save editor and I got to the Problem that I can't open my save files when I played on them.

I can Open save Files after I downloaded a random save file but not when I try to edit a save file Which I already palyed on 

But everything else is working fine!

**Comment by gibbed** [comment]
I need more information than that.

How is it failing? Are you getting an error message?

**Comment by Bluurix** [comment]
It only says reencode missmatch

I already read that up and it says I need the latest version of the editor which I downloaded yesterday

So to test things I downloaded a save File that skipped the beginning so I could Start at sanctuary 
I edited The character to start with lvl 15 on Sactuary and edited some other things into the save file.

I tested it and everything went fine so far. But after that I wanted to add some currency to the same save file.
I tried to Open the save file and It suddenly said reencode mismatch and I don't know why.

**Comment by gibbed** [comment]
Please attach the save file with the problem to this issue.

**Comment by Bluurix** [comment]
[Save0004.zip](https://github.com/gibbed/Gibbed.Borderlands2/files/1438459/Save0004.zip)

**Comment by gibbed** [comment]
When you say you downloaded the latest version of the editor, did you (grab it from the GitHub releases)[https://github.com/gibbed/Gibbed.Borderlands2/releases/latest] or something else?

That save is loading fine in the latest GitHub release of the save editor.

**Comment by Bluurix** [comment]
I downloaded it from here... 
![unbenannt](https://user-images.githubusercontent.com/33322909/32337928-98591b06-bff3-11e7-92f5-af90e0683d80.JPG)

The file Won't load :(

**Comment by gibbed** [comment]
I don't think you attached the correct save file then, Save004 is loading fine here.

**Comment by Bluurix** [comment]
I tried it with the same File now and I still have the Problem.... am I doing something wrong? 

I start the Editor and Select Open and It worked so Far with every File Except for the Files Which I already played on... it's kind of strange :/

**Comment by gibbed** [comment]
I don't know what to tell you, the save file you uploaded, `Save0004.sav`, is loading correctly in the latest release for me.

![gibbed s borderlands 2 save editor a334c91 10312017 624 pm](https://user-images.githubusercontent.com/85170/32338449-c8f1782a-bfc2-11e7-9199-93f5826aa80b.png)

**Comment by Bluurix** [comment]
okay, this is strange I downloaded It again and now it works without a Problem.

**Comment by gibbed** [comment]
The save itself or the save editor?

**Comment by Bluurix** [comment]
Both works fine now I really don't understand it

**Comment by gibbed** [comment]
Okay, if you have further problems open a new issue.
