### ISSUE TITLE
Gibbed not supporting equipment from Lilith DLC

### ISSUE THREAD

**Issue by ShinkuTear** [gibbed/Gibbed.Borderlands2#100]
I played through the Commander Lilith DLC, and found a number of new equips, and I placed them into the bank for later. After updating Gibbed to 1.0.16, I tried to load that character in Gibbed, and was given an error.

"There were weapons or items in the bank that failed to load. Do you want to remove them? If you choose not to remove them, they will remain in your save but will not be editable."

[oops.txt](https://github.com/gibbed/Gibbed.Borderlands2/files/3284189/oops.txt)

That is the error info that Gibbed copies to clipboard if I select to Cancel.

I specifically selected "bl2_saveedit_1.0.16.zip" to download for updating, in case this could affect it.

**Comment by gibbed** [comment]
Could you attach the save file?

**Comment by ShinkuTear** [comment]
[Save0004.zip](https://github.com/gibbed/Gibbed.Borderlands2/files/3284259/Save0004.zip)

This should be the correct save, should be a Lv63 Maya.

**Comment by gibbed** [comment]
This save loads just fine. Please make sure you're actually running the new version of the save editor.
