### ISSUE TITLE
Cant change weapon "Set dlc"

### ISSUE THREAD

**Issue by disk95** [gibbed/Gibbed.Borderlands2#101]
So when I open my save game and i want to make new weapon ex: I want to create Sand hawk from Pirate's Booty DLC so i cant click on "Base Game" like on the image
![111](https://user-images.githubusercontent.com/22323626/59466308-527b5e00-8e2d-11e9-89b6-596e2a61234b.png)

**Comment by gibbed** [comment]
That can't be changed. Use the dropdown on "New Weapon" to select a DLC.

**Comment by disk95** [comment]
Oh yea ! Thank you ^^
