### ISSUE TITLE
New DLC Weapons Not Creatable 

### ISSUE THREAD

**Issue by estovall** [gibbed/Gibbed.Borderlands2#102]
im trying to make some of the new rainbow guns from the newest version (10.1.16) of the editor that has the Commander Lilith and the Fight for Sanctuary DLC, but whenever you try to make any of them the bar turns red and none of the body types, barrels, manufacturer, etc. pops up.
![image](https://user-images.githubusercontent.com/30396927/59499968-1f9d8e00-8e5e-11e9-85c3-857631890f25.png)
here is a screenshot of what im talking about.

**Comment by gibbed** [comment]
You need to create it as a DLC weapon. Use the dropdown next to "New Weapon" to pick a DLC.
