### ISSUE TITLE
Error opening Gibbed (1.0.19)

### ISSUE THREAD

**Issue by NyanDynamiX** [gibbed/Gibbed.Borderlands2#103]
I get this error when trying to open the latest gibbed version. Any ideas?
---------------------------
Error
---------------------------
An exception was thrown (press Ctrl+C to copy):

System.ComponentModel.Composition.CompositionException: The composition produced a single composition error, with 2 root causes. The root causes are provided below. Review the CompositionException.Errors property for more detailed information.

1) Field not found: 'Gibbed.Borderlands2.GameInfo.DownloadablePackageDefinition.Default'.

Resulting in: The type initializer for 'Gibbed.Borderlands2.SaveEdit.BackpackViewModel' threw an exception.

Resulting in: An exception occurred while trying to create an instance of type 'Gibbed.Borderlands2.SaveEdit.BackpackViewModel'.

Resulting in: Cannot get export 'Gibbed.Borderlands2.SaveEdit.BackpackViewModel (ContractName="Gibbed.Borderlands2.SaveEdit.BackpackViewModel")' from part 'Gibbed.Borderlands2.SaveEdit.BackpackViewModel'.

Element: Gibbed.Borderlands2.SaveEdit.BackpackViewModel (ContractName="Gibbed.Borderlands2.SaveEdit.BackpackViewModel") -->  Gibbed.Borderlands2.SaveEdit.BackpackViewModel -->  AssemblyCatalog (Assembly="Gibbed.Borderlands2.SaveEdit, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null")

Resulting in: Cannot set import 'Gibbed.Borderlands2.SaveEdit.BankViewModel.Backpack (ContractName="Gibbed.Borderlands2.SaveEdit.BackpackViewModel")' on part 'Gibbed.Borderlands2.SaveEdit.BankViewModel'.

Element: Gibbed.Borderlands2.SaveEdit.BankViewModel.Backpack (ContractName="Gibbed.Borderlands2.SaveEdit.BackpackViewModel") -->  Gibbed.Borderlands2.SaveEdit.BankViewModel -->  AssemblyCatalog (Assembly="Gibbed.Borderlands2.SaveEdit, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null")

Resulting in: Cannot get export 'Gibbed.Borderlands2.SaveEdit.BankViewModel (ContractName="Gibbed.Borderlands2.SaveEdit.BankViewModel")' from part 'Gibbed.Borderlands2.SaveEdit.BankViewModel'.

Element: Gibbed.Borderlands2.SaveEdit.BankViewModel (ContractName="Gibbed.Borderlands2.SaveEdit.BankViewModel") -->  Gibbed.Borderlands2.SaveEdit.BankViewModel -->  AssemblyCatalog (Assembly="Gibbed.Borderlands2.SaveEdit, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null")

Resulting in: Cannot set import 'Gibbed.Borderlands2.SaveEdit.BackpackViewModel.Bank (ContractName="Gibbed.Borderlands2.SaveEdit.BankViewModel")' on part 'Gibbed.Borderlands2.SaveEdit.BackpackViewModel'.

Element: Gibbed.Borderlands2.SaveEdit.BackpackViewModel.Bank (ContractName="Gibbed.Borderlands2.SaveEdit.BankViewModel") -->  Gibbed.Borderlands2.SaveEdit.BackpackViewModel -->  AssemblyCatalog (Assembly="Gibbed.Borderlands2.SaveEdit, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null")

Resulting in: Cannot get export 'Gibbed.Borderlands2.SaveEdit.BackpackViewModel (ContractName="Gibbed.Borderlands2.SaveEdit.BackpackViewModel")' from part 'Gibbed.Borderlands2.SaveEdit.BackpackViewModel'.

Element: Gibbed.Borderlands2.SaveEdit.BackpackViewModel (ContractName="Gibbed.Borderlands2.SaveEdit.BackpackViewModel") -->  Gibbed.Borderlands2.SaveEdit.BackpackViewModel -->  AssemblyCatalog (Assembly="Gibbed.Borderlands2.SaveEdit, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null")

Resulting in: Cannot set import 'Gibbed.Borderlands2.SaveEdit.ShellViewModel.Backpack (ContractName="Gibbed.Borderlands2.SaveEdit.BackpackViewModel")' on part 'Gibbed.Borderlands2.SaveEdit.ShellViewModel'.

Element: Gibbed.Borderlands2.SaveEdit.ShellViewModel.Backpack (ContractName="Gibbed.Borderlands2.SaveEdit.BackpackViewModel") -->  Gibbed.Borderlands2.SaveEdit.ShellViewModel -->  AssemblyCatalog (Assembly="Gibbed.Borderlands2.SaveEdit, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null")

Resulting in: Cannot get export 'Gibbed.Borderlands2.SaveEdit.ShellViewModel (ContractName="Gibbed.Borderlands2.SaveEdit.ShellViewModel")' from part 'Gibbed.Borderlands2.SaveEdit.ShellViewModel'.

Element: Gibbed.Borderlands2.SaveEdit.ShellViewModel (ContractName="Gibbed.Borderlands2.SaveEdit.ShellViewModel") -->  Gibbed.Borderlands2.SaveEdit.ShellViewModel -->  AssemblyCatalog (Assembly="Gibbed.Borderlands2.SaveEdit, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null")

2) Field not found: 'Gibbed.Borderlands2.GameInfo.DownloadablePackageDefinition.Default'.

Resulting in: The type initializer for 'Gibbed.Borderlands2.SaveEdit.BankViewModel' threw an exception.

Resulting in: An exception occurred while trying to create an instance of type 'Gibbed.Borderlands2.SaveEdit.BankViewModel'.

Resulting in: Cannot get export 'Gibbed.Borderlands2.SaveEdit.BankViewModel (ContractName="Gibbed.Borderlands2.SaveEdit.BankViewModel")' from part 'Gibbed.Borderlands2.SaveEdit.BankViewModel'.

Element: Gibbed.Borderlands2.SaveEdit.BankViewModel (ContractName="Gibbed.Borderlands2.SaveEdit.BankViewModel") -->  Gibbed.Borderlands2.SaveEdit.BankViewModel -->  AssemblyCatalog (Assembly="Gibbed.Borderlands2.SaveEdit, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null")

Resulting in: Cannot set import 'Gibbed.Borderlands2.SaveEdit.BackpackViewModel.Bank (ContractName="Gibbed.Borderlands2.SaveEdit.BankViewModel")' on part 'Gibbed.Borderlands2.SaveEdit.BackpackViewModel'.

Element: Gibbed.Borderlands2.SaveEdit.BackpackViewModel.Bank (ContractName="Gibbed.Borderlands2.SaveEdit.BankViewModel") -->  Gibbed.Borderlands2.SaveEdit.BackpackViewModel -->  AssemblyCatalog (Assembly="Gibbed.Borderlands2.SaveEdit, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null")

Resulting in: Cannot get export 'Gibbed.Borderlands2.SaveEdit.BackpackViewModel (ContractName="Gibbed.Borderlands2.SaveEdit.BackpackViewModel")' from part 'Gibbed.Borderlands2.SaveEdit.BackpackViewModel'.

Element: Gibbed.Borderlands2.SaveEdit.BackpackViewModel (ContractName="Gibbed.Borderlands2.SaveEdit.BackpackViewModel") -->  Gibbed.Borderlands2.SaveEdit.BackpackViewModel -->  AssemblyCatalog (Assembly="Gibbed.Borderlands2.SaveEdit, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null")

Resulting in: Cannot set import 'Gibbed.Borderlands2.SaveEdit.BankViewModel.Backpack (ContractName="Gibbed.Borderlands2.SaveEdit.BackpackViewModel")' on part 'Gibbed.Borderlands2.SaveEdit.BankViewModel'.

Element: Gibbed.Borderlands2.SaveEdit.BankViewModel.Backpack (ContractName="Gibbed.Borderlands2.SaveEdit.BackpackViewModel") -->  Gibbed.Borderlands2.SaveEdit.BankViewModel -->  AssemblyCatalog (Assembly="Gibbed.Borderlands2.SaveEdit, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null")

Resulting in: Cannot get export 'Gibbed.Borderlands2.SaveEdit.BankViewModel (ContractName="Gibbed.Borderlands2.SaveEdit.BankViewModel")' from part 'Gibbed.Borderlands2.SaveEdit.BankViewModel'.

Element: Gibbed.Borderlands2.SaveEdit.BankViewModel (ContractName="Gibbed.Borderlands2.SaveEdit.BankViewModel") -->  Gibbed.Borderlands2.SaveEdit.BankViewModel -->  AssemblyCatalog (Assembly="Gibbed.Borderlands2.SaveEdit, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null")

Resulting in: Cannot set import 'Gibbed.Borderlands2.SaveEdit.ShellViewModel.Bank (ContractName="Gibbed.Borderlands2.SaveEdit.BankViewModel")' on part 'Gibbed.Borderlands2.SaveEdit.ShellViewModel'.

Element: Gibbed.Borderlands2.SaveEdit.ShellViewModel.Bank (ContractName="Gibbed.Borderlands2.SaveEdit.BankViewModel") -->  Gibbed.Borderlands2.SaveEdit.ShellViewModel -->  AssemblyCatalog (Assembly="Gibbed.Borderlands2.SaveEdit, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null")

Resulting in: Cannot get export 'Gibbed.Borderlands2.SaveEdit.ShellViewModel (ContractName="Gibbed.Borderlands2.SaveEdit.ShellViewModel")' from part 'Gibbed.Borderlands2.SaveEdit.ShellViewModel'.

Element: Gibbed.Borderlands2.SaveEdit.ShellViewModel (ContractName="Gibbed.Borderlands2.SaveEdit.ShellViewModel") -->  Gibbed.Borderlands2.SaveEdit.ShellViewModel -->  AssemblyCatalog (Assembly="Gibbed.Borderlands2.SaveEdit, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null")

   at System.ComponentModel.Composition.Hosting.CompositionServices.GetExportedValueFromComposedPart(ImportEngine engine, ComposablePart part, ExportDefinition definition)

   at System.ComponentModel.Composition.Hosting.CatalogExportProvider.GetExportedValue(CatalogPart part, ExportDefinition export, Boolean isSharedPart)

   at System.ComponentModel.Composition.Primitives.Export.get_Value()

   at System.ComponentModel.Composition.ExportServices.GetCastedExportedValue[T](Export export)

   at System.ComponentModel.Composition.Hosting.ExportProvider.GetExportedValuesCore[T](String contractName)

   at Gibbed.Borderlands2.SaveEdit.AppBootstrapper.GetInstance(Type serviceType, String key) in c:\projects\gibbed-borderlands2\projects\Gibbed.Borderlands2.SaveEdit\AppBootstrapper.cs:line 75

   at Caliburn.Micro.BootstrapperBase.DisplayRootViewFor(Type viewModelType)

   at Gibbed.Borderlands2.SaveEdit.AppBootstrapper.OnStartup(Object sender, StartupEventArgs e) in c:\projects\gibbed-borderlands2\projects\Gibbed.Borderlands2.SaveEdit\AppBootstrapper.cs:line 100
---------------------------
OK   
---------------------------

**Comment by NyanDynamiX** [comment]
A little update: The Debug version works but the normal one doesn't. Is it safe to just use the Debug vesion or is there any difference to the normal version?

**Comment by NyanDynamiX** [comment]
Oh another update:Normal one works if i put it in an isolated folder. Ill close this issue now (I've always launched it in a different directory but it seems its just my file pathing)

Thanks for the update!

**Comment by gibbed** [comment]
Yeah the only reason you should be getting an error like this is if you have a weird mixed version of the save editor.
