### ISSUE TITLE
Alien Launchers still broken.

### ISSUE THREAD

**Issue by B4LINT** [gibbed/Gibbed.Borderlands2#104]
In the newest version alien launcher materials are still broken:
I put this one together and its still dissappear when I load back to my game: https://imgur.com/CzBjgGj

I loaded up a save that has a legit farmed one:   https://imgur.com/kC2Ux4I

**Comment by gibbed** [comment]
Is this PC or console?

**Comment by B4LINT** [comment]
PC

**Comment by gibbed** [comment]
Okay. This is definitely an issue on my end with how I'm generating the combined balance data, but I haven't figured out what I'm doing wrong yet. The correct material for this weapon is `GD_Weap_Launchers.ManufacturerMaterials.Mat_Vladof_3`.

**Comment by gibbed** [comment]
Should be fixed as of https://github.com/gibbed/Gibbed.Borderlands2/commit/2488008458bd4c773178af4a9dc13a6ab0a9a938.
