### ISSUE TITLE
Cannot open; Massive error

### ISSUE THREAD

**Issue by marccost3** [gibbed/Gibbed.Borderlands2#105]
I downloaded version 1.0.19 and cannot open it. Previous versions worked fine, but 1.0.19 gives me this error: 

> 
> ---------------------------
> Error
> ---------------------------
> An exception was thrown (press Ctrl+C to copy):
> 
> System.ComponentModel.Composition.CompositionException: The composition produced a single composition error, with 2 root causes. The root causes are provided below. Review the CompositionException.Errors property for more detailed information.
> 
> 
> 
> 1) Field not found: 'Gibbed.Borderlands2.GameInfo.DownloadablePackageDefinition.Default'.
> 
> 
> 
> Resulting in: The type initializer for 'Gibbed.Borderlands2.SaveEdit.BackpackViewModel' threw an exception.
> 
> 
> 
> Resulting in: An exception occurred while trying to create an instance of type 'Gibbed.Borderlands2.SaveEdit.BackpackViewModel'.
> 
> 
> 
> Resulting in: Cannot get export 'Gibbed.Borderlands2.SaveEdit.BackpackViewModel (ContractName="Gibbed.Borderlands2.SaveEdit.BackpackViewModel")' from part 'Gibbed.Borderlands2.SaveEdit.BackpackViewModel'.
> 
> Element: Gibbed.Borderlands2.SaveEdit.BackpackViewModel (ContractName="Gibbed.Borderlands2.SaveEdit.BackpackViewModel") -->  Gibbed.Borderlands2.SaveEdit.BackpackViewModel -->  AssemblyCatalog (Assembly="Gibbed.Borderlands2.SaveEdit, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null")
> 
> 
> 
> Resulting in: Cannot set import 'Gibbed.Borderlands2.SaveEdit.BankViewModel.Backpack (ContractName="Gibbed.Borderlands2.SaveEdit.BackpackViewModel")' on part 'Gibbed.Borderlands2.SaveEdit.BankViewModel'.
> 
> Element: Gibbed.Borderlands2.SaveEdit.BankViewModel.Backpack (ContractName="Gibbed.Borderlands2.SaveEdit.BackpackViewModel") -->  Gibbed.Borderlands2.SaveEdit.BankViewModel -->  AssemblyCatalog (Assembly="Gibbed.Borderlands2.SaveEdit, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null")
> 
> 
> 
> Resulting in: Cannot get export 'Gibbed.Borderlands2.SaveEdit.BankViewModel (ContractName="Gibbed.Borderlands2.SaveEdit.BankViewModel")' from part 'Gibbed.Borderlands2.SaveEdit.BankViewModel'.
> 
> Element: Gibbed.Borderlands2.SaveEdit.BankViewModel (ContractName="Gibbed.Borderlands2.SaveEdit.BankViewModel") -->  Gibbed.Borderlands2.SaveEdit.BankViewModel -->  AssemblyCatalog (Assembly="Gibbed.Borderlands2.SaveEdit, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null")
> 
> 
> 
> Resulting in: Cannot set import 'Gibbed.Borderlands2.SaveEdit.BackpackViewModel.Bank (ContractName="Gibbed.Borderlands2.SaveEdit.BankViewModel")' on part 'Gibbed.Borderlands2.SaveEdit.BackpackViewModel'.
> 
> Element: Gibbed.Borderlands2.SaveEdit.BackpackViewModel.Bank (ContractName="Gibbed.Borderlands2.SaveEdit.BankViewModel") -->  Gibbed.Borderlands2.SaveEdit.BackpackViewModel -->  AssemblyCatalog (Assembly="Gibbed.Borderlands2.SaveEdit, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null")
> 
> 
> 
> Resulting in: Cannot get export 'Gibbed.Borderlands2.SaveEdit.BackpackViewModel (ContractName="Gibbed.Borderlands2.SaveEdit.BackpackViewModel")' from part 'Gibbed.Borderlands2.SaveEdit.BackpackViewModel'.
> 
> Element: Gibbed.Borderlands2.SaveEdit.BackpackViewModel (ContractName="Gibbed.Borderlands2.SaveEdit.BackpackViewModel") -->  Gibbed.Borderlands2.SaveEdit.BackpackViewModel -->  AssemblyCatalog (Assembly="Gibbed.Borderlands2.SaveEdit, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null")
> 
> 
> 
> Resulting in: Cannot set import 'Gibbed.Borderlands2.SaveEdit.ShellViewModel.Backpack (ContractName="Gibbed.Borderlands2.SaveEdit.BackpackViewModel")' on part 'Gibbed.Borderlands2.SaveEdit.ShellViewModel'.
> 
> Element: Gibbed.Borderlands2.SaveEdit.ShellViewModel.Backpack (ContractName="Gibbed.Borderlands2.SaveEdit.BackpackViewModel") -->  Gibbed.Borderlands2.SaveEdit.ShellViewModel -->  AssemblyCatalog (Assembly="Gibbed.Borderlands2.SaveEdit, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null")
> 
> 
> 
> Resulting in: Cannot get export 'Gibbed.Borderlands2.SaveEdit.ShellViewModel (ContractName="Gibbed.Borderlands2.SaveEdit.ShellViewModel")' from part 'Gibbed.Borderlands2.SaveEdit.ShellViewModel'.
> 
> Element: Gibbed.Borderlands2.SaveEdit.ShellViewModel (ContractName="Gibbed.Borderlands2.SaveEdit.ShellViewModel") -->  Gibbed.Borderlands2.SaveEdit.ShellViewModel -->  AssemblyCatalog (Assembly="Gibbed.Borderlands2.SaveEdit, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null")
> 
> 
> 
> 2) Field not found: 'Gibbed.Borderlands2.GameInfo.DownloadablePackageDefinition.Default'.
> 
> 
> 
> Resulting in: The type initializer for 'Gibbed.Borderlands2.SaveEdit.BankViewModel' threw an exception.
> 
> 
> 
> Resulting in: An exception occurred while trying to create an instance of type 'Gibbed.Borderlands2.SaveEdit.BankViewModel'.
> 
> 
> 
> Resulting in: Cannot get export 'Gibbed.Borderlands2.SaveEdit.BankViewModel (ContractName="Gibbed.Borderlands2.SaveEdit.BankViewModel")' from part 'Gibbed.Borderlands2.SaveEdit.BankViewModel'.
> 
> Element: Gibbed.Borderlands2.SaveEdit.BankViewModel (ContractName="Gibbed.Borderlands2.SaveEdit.BankViewModel") -->  Gibbed.Borderlands2.SaveEdit.BankViewModel -->  AssemblyCatalog (Assembly="Gibbed.Borderlands2.SaveEdit, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null")
> 
> 
> 
> Resulting in: Cannot set import 'Gibbed.Borderlands2.SaveEdit.BackpackViewModel.Bank (ContractName="Gibbed.Borderlands2.SaveEdit.BankViewModel")' on part 'Gibbed.Borderlands2.SaveEdit.BackpackViewModel'.
> 
> Element: Gibbed.Borderlands2.SaveEdit.BackpackViewModel.Bank (ContractName="Gibbed.Borderlands2.SaveEdit.BankViewModel") -->  Gibbed.Borderlands2.SaveEdit.BackpackViewModel -->  AssemblyCatalog (Assembly="Gibbed.Borderlands2.SaveEdit, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null")
> 
> 
> 
> Resulting in: Cannot get export 'Gibbed.Borderlands2.SaveEdit.BackpackViewModel (ContractName="Gibbed.Borderlands2.SaveEdit.BackpackViewModel")' from part 'Gibbed.Borderlands2.SaveEdit.BackpackViewModel'.
> 
> Element: Gibbed.Borderlands2.SaveEdit.BackpackViewModel (ContractName="Gibbed.Borderlands2.SaveEdit.BackpackViewModel") -->  Gibbed.Borderlands2.SaveEdit.BackpackViewModel -->  AssemblyCatalog (Assembly="Gibbed.Borderlands2.SaveEdit, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null")
> 
> 
> 
> Resulting in: Cannot set import 'Gibbed.Borderlands2.SaveEdit.BankViewModel.Backpack (ContractName="Gibbed.Borderlands2.SaveEdit.BackpackViewModel")' on part 'Gibbed.Borderlands2.SaveEdit.BankViewModel'.
> 
> Element: Gibbed.Borderlands2.SaveEdit.BankViewModel.Backpack (ContractName="Gibbed.Borderlands2.SaveEdit.BackpackViewModel") -->  Gibbed.Borderlands2.SaveEdit.BankViewModel -->  AssemblyCatalog (Assembly="Gibbed.Borderlands2.SaveEdit, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null")
> 
> 
> 
> Resulting in: Cannot get export 'Gibbed.Borderlands2.SaveEdit.BankViewModel (ContractName="Gibbed.Borderlands2.SaveEdit.BankViewModel")' from part 'Gibbed.Borderlands2.SaveEdit.BankViewModel'.
> 
> Element: Gibbed.Borderlands2.SaveEdit.BankViewModel (ContractName="Gibbed.Borderlands2.SaveEdit.BankViewModel") -->  Gibbed.Borderlands2.SaveEdit.BankViewModel -->  AssemblyCatalog (Assembly="Gibbed.Borderlands2.SaveEdit, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null")
> 
> 
> 
> Resulting in: Cannot set import 'Gibbed.Borderlands2.SaveEdit.ShellViewModel.Bank (ContractName="Gibbed.Borderlands2.SaveEdit.BankViewModel")' on part 'Gibbed.Borderlands2.SaveEdit.ShellViewModel'.
> 
> Element: Gibbed.Borderlands2.SaveEdit.ShellViewModel.Bank (ContractName="Gibbed.Borderlands2.SaveEdit.BankViewModel") -->  Gibbed.Borderlands2.SaveEdit.ShellViewModel -->  AssemblyCatalog (Assembly="Gibbed.Borderlands2.SaveEdit, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null")
> 
> 
> 
> Resulting in: Cannot get export 'Gibbed.Borderlands2.SaveEdit.ShellViewModel (ContractName="Gibbed.Borderlands2.SaveEdit.ShellViewModel")' from part 'Gibbed.Borderlands2.SaveEdit.ShellViewModel'.
> 
> Element: Gibbed.Borderlands2.SaveEdit.ShellViewModel (ContractName="Gibbed.Borderlands2.SaveEdit.ShellViewModel") -->  Gibbed.Borderlands2.SaveEdit.ShellViewModel -->  AssemblyCatalog (Assembly="Gibbed.Borderlands2.SaveEdit, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null")
> 
> 
> 
>    at System.ComponentModel.Composition.Hosting.CompositionServices.GetExportedValueFromComposedPart(ImportEngine engine, ComposablePart part, ExportDefinition definition)
> 
>    at System.ComponentModel.Composition.Hosting.CatalogExportProvider.GetExportedValue(CatalogPart part, ExportDefinition export, Boolean isSharedPart)
> 
>    at System.ComponentModel.Composition.Primitives.Export.get_Value()
> 
>    at System.ComponentModel.Composition.ExportServices.GetCastedExportedValue[T](Export export)
> 
>    at System.ComponentModel.Composition.Hosting.ExportProvider.GetExportedValuesCore[T](String contractName)
> 
>    at Gibbed.Borderlands2.SaveEdit.AppBootstrapper.GetInstance(Type serviceType, String key)
> 
>    at Caliburn.Micro.BootstrapperBase.DisplayRootViewFor(Type viewModelType)
> 
>    at Gibbed.Borderlands2.SaveEdit.AppBootstrapper.OnStartup(Object sender, StartupEventArgs e)
> ---------------------------
> OK   
> ---------------------------
>

**Comment by gibbed** [comment]
You probably have a incorrectly mixed copy of the save editor. Please remove all existing save editor files and redownload the latest version.

**Comment by marccost3** [comment]
I had already tried that, and it still didn't work. However, once I also removed the "assemblies" folder, it worked. Thank you.
