### ISSUE TITLE
Creating DLC relic problem

### ISSUE THREAD

**Issue by Spectatroll** [gibbed/Gibbed.Borderlands2#106]
Creating some certain relics from DLC might be a problem if you dont have the correct combination of the Alpha, Beta, Gamma.. ETC, i mean it should show the correct ones, because if it doesnt, the created item would just disappear(IDK wether this was caused by my game or not, but i do have the DLC)
take this image for instance
![EG](https://user-images.githubusercontent.com/20752678/59929142-c7c0e180-9472-11e9-98d1-f63c116541d5.png)
this one works but. making the Gladiolus ElementalProficiency Artifact
the Manufacturer, Alpha, and Beta has to be in order. otherwise the the created relic would just disappear or deleted by the game when you open the bag/bank where u created the item
so if you choose
Manufacturer : typeA
the Alpha must be : Effect1
and Beta must be : Effect4

otherwise choosing different combination like M : TypeB, A : Effect3, B : Effect5, would make the created relic just disappear when you open the storage where u created them

**Comment by gibbed** [comment]
This is a problem I'm currently working on, but have not solved yet.

**Comment by gibbed** [comment]
Should be fixed as of 1a26a0123b3f3296e5f6361e055b2170706a9a41.
