### ISSUE TITLE
Error every time i open an edited savefile

### ISSUE THREAD

**Issue by whyisntthisworking-exe** [gibbed/Gibbed.Borderlands2#109]
---------------------------
Error
---------------------------
An exception was thrown (press Ctrl+C to copy):

Gibbed.Borderlands2.GameInfo.ResourceNotFoundException: item type 'GD_ClassMods.A_Item_Merc.ClassMod_Merc_Tank' is not valid for 'GD_ItemGrades.ClassMods.BalDef_ClassMod_Mercenary_05_Legendary'

   bei Gibbed.Borderlands2.GameInfo.ItemBalanceDefinition.Create(ItemDefinition item)

   bei Gibbed.Borderlands2.SaveEdit.BaseItemViewModel.BuildPartAssets()

   bei Gibbed.Borderlands2.SaveEdit.BaseItemViewModel..ctor(BaseItem item)

   bei Gibbed.Borderlands2.SaveEdit.BackpackItemViewModel..ctor(BackpackItem item)

   bei Gibbed.Borderlands2.SaveEdit.BackpackViewModel.ImportData(WillowTwoPlayerSaveGame saveGame, Platform platform)

   bei Gibbed.Borderlands2.SaveEdit.ShellViewModel.<>c__DisplayClass62_0.<ReadSave>b__0()

   bei Caliburn.Micro.Contrib.Results.DelegateResult.Execute(ActionExecutionContext context)
---------------------------
OK   
---------------------------
any tips on how to fix this?

**Comment by gibbed** [comment]
1. Make sure you have a clean install of the [latest release](https://github.com/gibbed/Gibbed.Borderlands2/releases/latest).
1. If you're still having the issue, please attach the save file with the issue to this issue.

**Comment by gibbed** [comment]
Grab the new [1.0.42 release](https://github.com/gibbed/Gibbed.Borderlands2/releases/latest) (or newer) which has a fix for this problem.
