### ISSUE TITLE
Two wrong weapon parts that shouldn't show up as "Unsupported value"

### ISSUE THREAD

**Issue by Natsu235** [gibbed/Gibbed.Borderlands2#11]
I have found 2 small issues in the save editor with weapon parts showing up as "Unsupported value":

- All E-tech launchers use wrong "Material" in the game. Purple Rarity "Material" are used in game instead of E-tech "Material" for launchers. So for example for Vladof E-tech launchers, the save editor should show "GD_Weap_Launchers.ManufacturerMaterials.Mat_Vladof_4" and make "GD_Weap_Launchers.ManufacturerMaterials.Mat_Vladof_5" as "Unsupported value" instead.

http://s1380.photobucket.com/user/Natsu235/media/BL2_Gibbed_Issue_01_zpsuzxtidxz.png.html

- On November 21, 2013 a patch fixed the "Crit" SMG to prevent it to spawn as a Purple Rarity weapon and make it Blue Rarity instead (same problem with "Bad Touch" and "Good Touch" but were never fixed for some reasons). The "Body" part was changed from "GD_Weap_SMG.Body.SMG_Body_Maliwan_VarC" to "GD_Weap_SMG.Body.SMG_Body_Maliwan_VarB". So the save editor should not show "Unsupported value" on VarB Body for the Crit.

http://s1380.photobucket.com/user/Natsu235/media/BL2_Gibbed_Issue_02_zpsljjyyiqd.png.html

Hope it helps.
And btw, are you planning to do a "Fast Travel" tab to Pre-Sequel save editor or is there any reason to not have made it ?

**Comment by gibbed** [comment]
Should be fixed as of https://github.com/gibbed/Gibbed.Borderlands2/commit/844ce3427b877f8c8d032df1434fe9dd3edabe86.
