### ISSUE TITLE
not really an issue, more of question for level challenge unlocks

### ISSUE THREAD

**Issue by warlord1352** [gibbed/Gibbed.Borderlands2#110]
sorry for posting this here, and sorry if this has already been discussed. What exactly is the "LevelChallengeUnlocks" under the raw tab? I am trying to find where to can manipulate (if possible) the Badass challenges.

*Edit: Also might as well add what is the "OneOffLevelChallengeCompletion"*

**Comment by gibbed** [comment]
I never investigated what those are for, but badass data is stored as part of your profile, which is not in save data.

**Comment by warlord1352** [comment]
Ah ok, thanks for the quick response too!
