### ISSUE TITLE
New Borderlands Update Causes Startup Crash

### ISSUE THREAD

**Issue by Stevester118** [gibbed/Gibbed.Borderlands2#115]
Since the update on 7/1/2019, after editing a save and saving it, Borderlands 2 crashes on startup after clicking the play on the splash screen

**Comment by gibbed** [comment]
There has been no recent update the game?

**Comment by Stevester118** [comment]
You are right, that was stupid of me. I forgot I purchased the skin packs because they were super cheap so thats what was downloaded for Borderlands. I'm gonna try and figure out what was causing the startup crash. Maybe I input something invalid somewhere

**Comment by Stevester118** [comment]
Yeah I definitely input something invalid because it is working now. My apologies for this.
