### ISSUE TITLE
Error preventing me from Opening Saves

### ISSUE THREAD

**Issue by LithiumMonoxide** [gibbed/Gibbed.Borderlands2#120]
This is the error:

---------------------------
Error
---------------------------
An exception was thrown (press Ctrl+C to copy):

System.MissingMethodException: Method not found: 'System.String Gibbed.IO.StreamHelpers.ReadString(System.IO.Stream, Int32)'.

   at Gibbed.Borderlands2.FileFormats.SaveFile.Deserialize(Stream input, Platform platform, DeserializeSettings settings)

   at Gibbed.Borderlands2.SaveEdit.ShellViewModel.<>c__DisplayClass62_0.<ReadSave>b__0()

   at Caliburn.Micro.Contrib.Results.DelegateResult.Execute(ActionExecutionContext context)
---------------------------
OK   
---------------------------

I dont quite understand what this means, im knew to save editing and dont know much about gibbed.

**Comment by LithiumMonoxide** [comment]
![BL2Error](https://user-images.githubusercontent.com/52897494/61190903-ef6e2880-a671-11e9-8f6d-5570306e1405.PNG)

**Comment by gibbed** [comment]
You have mixed versions of the save editor in the same location. Either clean up the directory and remove the old files or extract the save editor files to a new directory.

**Comment by LithiumMonoxide** [comment]
thank you
