### ISSUE TITLE
GitHub issues preventing downloading of releases

### ISSUE THREAD

**Issue by Redllama-king** [gibbed/Gibbed.Borderlands2#121]
Attempting to download the files - I get a server 500 error.

**Comment by gibbed** [comment]
Yeah looks like this is an issue on GitHub's end.

**Comment by gibbed** [comment]
https://www.githubstatus.com/

Looks like they're investigating. If you like you can [follow me on Twitter](https://twitter.com/gibbed) and I'll tweet out when it's resolved.

**Comment by gibbed** [comment]
I'll also update this issue as well.

**Comment by gibbed** [comment]
This may be resolved? GitHub status page now showing degraded performance and release downloads are working for me.

I'll leave this issue open until status is green again though.

**Comment by Redllama-king** [comment]
Thanks for the update - it's working now.
