### ISSUE TITLE
Failed: reencode mismatch

### ISSUE THREAD

**Issue by kingkrieg** [gibbed/Gibbed.Borderlands2#13]
I am trying to load a saved game and edit it, how do I actually do it? Ive downloaded saveedit-1.0.5.zip and extracted it to the borderlands2 folder. And how do play a new game with a character I make using the editor from scratch?

**Comment by kingkrieg** [comment]
Ok I made a new file and it played fine, still unable to load it though, and I'm not sure how to attach it, it says we don't support that file type.

**Comment by gibbed** [comment]
You'll need to archive the file somehow, probably into a ZIP file.

**Comment by kingkrieg** [comment]
Thanks [Save0002.zip](https://github.com/gibbed/Gibbed.Borderlands2/files/1476159/Save0002.zip)

**Comment by kingkrieg** [comment]
I got it to work. Its so funny, I saw on another issue just like mine you said that other guys file was working just fine on your end, so tried opening his and my file link above...and they worked. Now I can open all my save files, I don't know why but whatever works.

**Comment by gibbed** [comment]
Great.
