### ISSUE TITLE
Reencode mismatch

### ISSUE THREAD

**Issue by SilverCreepy** [gibbed/Gibbed.Borderlands2#14]
Hey, I might be doing it wrong, but i can't load my save in. Please help me if you can. Thanks, Silver
![image](https://user-images.githubusercontent.com/33666418/32794486-4cf9e3fa-c969-11e7-850b-248dae7bfe6c.png)
![image](https://user-images.githubusercontent.com/33666418/32794496-57073fe6-c969-11e7-8c71-0e08fa87de3b.png)
![image](https://user-images.githubusercontent.com/33666418/32794504-5e8c1908-c969-11e7-98b6-7e6acef40dc7.png)
![image](https://user-images.githubusercontent.com/33666418/32794508-60d5c63c-c969-11e7-8aa8-499460f6602d.png)

**Comment by SilverCreepy** [comment]
Sorry, I'm retard, just noticed i was using a wrong release :D

**Comment by gibbed** [comment]
That would do it. Glad you got it sorted.
