### ISSUE TITLE
Cannot load Nintendo Switch save

### ISSUE THREAD

**Issue by switchGva** [gibbed/Gibbed.Borderlands2#142]
Extracted my save with Checkpoint
Error : Failed to load save: invalid SHA1 hash

(note : same error if I create a switch save from scratch)

**Comment by gibbed** [comment]
Please attach the save to this issue in a comment.

**Comment by switchGva** [comment]
[SaveData.zip](https://github.com/gibbed/Gibbed.Borderlands2/files/4724738/SaveData.zip)


Save0001.sav comes from the Switch
toto.sav is a dummy save I created with SaveEdit (last release)

**Comment by ajax-47** [comment]
Same issue here, attached both of my saves. 
[SaveData.zip](https://github.com/gibbed/Gibbed.Borderlands2/files/4726660/SaveData.zip)

Have also seen other reports of the SHA error

ps, Thank you so much for updating this!  Wonderful to continue my pc save on switch <3

**Comment by switchGva** [comment]
Wow, that worked. Slightly counter intuitive to see the file in windows file opener but not being able to open it without changing the type of file. 

Thanks you for the answer, and gibbed for the work.

**Comment by gibbed** [comment]
Ah, yeah. Not much I can do about that since they all share the same file extension.
