### ISSUE TITLE
Strange contacted URLs, domains and IPs in virustotal report of .exe file of the last version

### ISSUE THREAD

**Issue by h1tech** [gibbed/Gibbed.Borderlands2#144]
Can someone describe what are these URLs and domains for?

**Comment by gibbed** [comment]
You're going to have to be more specific than that. Link this VirusTotal that you're claiming shows strange behavior.

The save editor doesn't open any connections to anything.

**Comment by h1tech** [comment]
Oh, yeah, here it is: https://www.virustotal.com/gui/file/167734b6b8a1ea2a9eaffd8ea53a34eb12eb13c628e259719ae300d8f2081932/relations

**Comment by gibbed** [comment]
Those are all clearly on Microsoft's servers, related to digital certificates. It's probably some .NET internal thing to fetch those, completely unrelated to the save editor.

VirusTotal didn't bat an eye on it, why are you?

**Comment by h1tech** [comment]
I am just very cautious and fearful and scaredof anything that can harm my pc. However, thanks for your help and your useful program!
