### ISSUE TITLE
reen code error plz help

### ISSUE THREAD

**Issue by butterboy210** [gibbed/Gibbed.Borderlands2#19]

**Comment by butterboy210** [comment]
what is the latest release and what do you mean correct editor

**Comment by gibbed** [comment]
That you're not trying to open a Borderlands 2 save in the editor for The Pre-Sequel or vice versa.

[The latest release](https://github.com/gibbed/Gibbed.Borderlands2/releases/latest).

**Comment by butterboy210** [comment]
I am sorry but how do you download I am new to this

**Comment by gibbed** [comment]
You want the saveedit-1.xx.zip file in the release link I gave above.

**Comment by butterboy210** [comment]
everything is working except for the guns

**Comment by gibbed** [comment]
Can you clarify what you mean?

**Comment by butterboy210** [comment]
for example I am trying to spawn a sandhawk and its doesn't show up or I end up getting a red outline around it

**Comment by Shibens** [comment]
I don't understand how to install any of this because there are six things to download.

**Comment by Shibens** [comment]
Can you do a step by step on how to install this

**Comment by gibbed** [comment]
@Shibens You want the "saveedit-1.x.x.zip" (currently "saveedit-1.0.5.zip"), none of the other downloads.

**Comment by Shibens** [comment]
Then how do I "activate" the thing

**Comment by gibbed** [comment]
@Shibens You unzip the archive and run the .exe?

**Comment by Shibens** [comment]
OK thanks  👍
