### ISSUE TITLE
Unable to launch save editor

### ISSUE THREAD

**Issue by NotHereSenpai** [gibbed/Gibbed.Borderlands2#2]
I downloaded this new version (from 256) and when browsing the files to launch the save editor, I could not find a launchable file.  Am I just blind and overlooking something, or is the file actually missing?

**Comment by gibbed** [comment]
@NotHereSenpai What file did you download?

**Comment by NotHereSenpai** [comment]
@gibbed I went to https://github.com/gibbed/Gibbed.Borderlands2 and downloaded it as a zip.  Unzipped it in my Windows Explorer.

**Comment by gibbed** [comment]
@NotHereSenpai You downloaded a copy of the source code. What you're after is a release.

https://github.com/gibbed/Gibbed.Borderlands2/releases

You want "saveedit-#.#.#.zip" (not "saveedit-#.#.#-with-symbols.zip").

**Comment by NotHereSenpai** [comment]
Awesome, thanks friend.
