### ISSUE TITLE
Problem with running program

### ISSUE THREAD

**Issue by Dialga1** [gibbed/Gibbed.Borderlands2#20]
So, uh i downloaded it and i cant figure out which file to run to get the save editor open, could you tell me which folders to go into in the unzipped file and what to run to get save editor open?

**Comment by gibbed** [comment]
You probably downloaded a ZIP of the repository (the source code).

You want to grab the latest saveedit-1.x.x.zip from releases.

https://github.com/gibbed/Gibbed.Borderlands2/releases/latest

**Comment by Dialga1** [comment]
Thank you gibbed!

**Comment by gibbed** [comment]
Did that fix your issue?

**Comment by Dialga1** [comment]
yes thank you!
