### ISSUE TITLE
Reencode Mismatch, Again.

### ISSUE THREAD

**Issue by TheDarkLord325** [gibbed/Gibbed.Borderlands2#21]
I have everything I have been told to get, including the latest version of Gibbed, Borderlands 2 all updated. I have reinstalled everything repeatedly to try to get this to work, it wont. Im at a total loss for what to do and would really like some help.

**Comment by TheDarkLord325** [comment]
Ok, I got a new character i made to work. But now i cannot access him again, all i get is the reencode mismatch. I would really like to get this fixed please.

**Comment by gibbed** [comment]
Verify that you are using the correct save editor and latest version of it.

If you are still having an issue, please attach a sample of the save file to this issue.

**Comment by TheDarkLord325** [comment]
[saveedit-1.0.5.zip](https://github.com/gibbed/Gibbed.Borderlands2/files/1546246/saveedit-1.0.5.zip)

[Save0003 - Copy.zip](https://github.com/gibbed/Gibbed.Borderlands2/files/1546248/Save0003.-.Copy.zip)

**Comment by TheDarkLord325** [comment]
i have unzipped and used the save edit, the save 0003 is the exact same one ive used for the gibbed editor

**Comment by poldi1405** [comment]
can confirm
samples:
[SaveSamples.zip](https://github.com/gibbed/Gibbed.Borderlands2/files/1576629/SaveSamples.zip)

**Comment by gibbed** [comment]
@poldi1405 All of those saves load fine in the current version of the editor. Please verify that you are using the correct save editor and latest version of it, available from the releases page.

https://github.com/gibbed/Gibbed.Borderlands2/releases

**Comment by poldi1405** [comment]
Probably a download error. Works after redownload

**Comment by TheDarkLord325** [comment]
i, supposed to use saveedit-10.5zip yes?

**Comment by gibbed** [comment]
@TheDarkLord325 Yes.

**Comment by TheDarkLord325** [comment]
and im supposed to save it to downloads first yes?

**Comment by gibbed** [comment]
You can do whatever, as long as you extract the contents to its own folder somewhere.

**Comment by TheDarkLord325** [comment]
it has to be in its own folder? so i cant just extract it to the borderlands folder?

**Comment by gibbed** [comment]
Make it a subfolder of that one then. It's not a good idea to mix official and unofficial software like that.

**Comment by TheDarkLord325** [comment]
ok, trying it now will report. sorry for the hassle i really like this kind of idea and the fact that you guys seem to have put a lot of work into it makes me not want to just right it of as a bad mod just cause i am an idiot

**Comment by TheDarkLord325** [comment]
Alright it worked thank you so very much. And great job on the mod you guys are awesome!

**Comment by poldi1405** [comment]
wow... my inability to download a file and check the hash solved this poblem
