### ISSUE TITLE
Unable to Open/run application

### ISSUE THREAD

**Issue by Smallgiant801** [gibbed/Gibbed.Borderlands2#29]
I downloaded all the files offered but am unable to start the application. Am I missing a .exe somewhere? I downloaded this after another version I had did not work with my PC saves.

**Comment by gibbed** [comment]
https://github.com/gibbed/Gibbed.Borderlands2/releases/latest

**Comment by Smallgiant801** [comment]
Great thanks I have it working now. 
Is it possible to take PC game save convert to Xbox 360 save then upload it to the cloud so I can have it on Xbox One?


Sent from Mail for Windows 10

**Comment by gibbed** [comment]
Unfortunately I don't know anything about console related save stuff, perhaps someone else could chime in on that?

**Comment by Smallgiant801** [comment]
Not sure if your interested but here is what I have learned.
It is possible, though quite the process to transfer PC game saves to the Xbox One.
1)create a number of dummy characters on Xbox 360, saved to thumb drive. 
2) access dummy characters on gibbed save editor and overlay the them with PC saves. PC saves must be converted to Xbox 360 saves before replacing the dummy 360 saves the Horizon program must used to access the Xbox 360 formatted thumb drive and compile the files. 
3)reload gibbed 360 files back onto the Xbox 360, transfer saves to the cloud. 
4)on the Xbox one access the saves from the cloud. 

I haven’t tried this as I don’t have a 360 anymore. With sometime and expertise this could be simplified by a way to directly access an Xbox live account and adding the saves there. Sadly that type of programming is way beyond me. 

Sent from Mail for Windows 10
