### ISSUE TITLE
BL2

### ISSUE THREAD

**Issue by ayorgie** [gibbed/Gibbed.Borderlands2#3]
Sorry I'm very new to this, and also very clueless. I'm looking for what I'm supposed to click to download but can't even figure that out.

**Comment by gibbed** [comment]
@ayorgie https://github.com/gibbed/Gibbed.Borderlands2/releases

You want "saveedit-#.#.#.zip" (not "saveedit-#.#.#-with-symbols.zip").

**Comment by ayorgie** [comment]
thanks so much!

**Comment by ayorgie** [comment]
I'm still getting the "Failed to load save:invalid or unsupported version" error

**Comment by gibbed** [comment]
@ayorgie What kind of save file are you trying to load?

**Comment by ayorgie** [comment]
I'm using a save file that i extracted from Horizon

**Comment by gibbed** [comment]
@ayorgie Are you selecting the correct platform in the open file dialog?

**Comment by ayorgie** [comment]
No, I was not. Looks to be working now, thanks.
