### ISSUE TITLE
Can't Run Gibbed

### ISSUE THREAD

**Issue by PainTNeT** [gibbed/Gibbed.Borderlands2#30]
I've got everything needed installed, I extract the zip file, but once I extract it there is only one folder. I've looked inside the folder but I can't find the icon that would open the program anywhere. I've re downloaded the GitHub file 3 times now and it's always the same. All help is very much appreciated.

**Comment by FromDarkHell** [comment]
https://github.com/gibbed/Gibbed.Borderlands2/releases/latest

**Comment by PainTNeT** [comment]
I am a teeny weeny bit retarded when it comes to things like this. I have the latest version but don't know what to download exactly, and what to do when nothing shows up. I do appreciate the help though.
