### ISSUE TITLE
reencode issue

### ISSUE THREAD

**Issue by Gotin-Drachenhart** [gibbed/Gibbed.Borderlands2#31]
Hello,

Thanks for the program! 

After a long break from BL a relative wanted to play so I fired up the game and no issues. Afterwards I wanted to just update some items to match the character's level. So I rolled out my trusty editor. But the save I'd just played on wouldn't load while giving me the reencode mismatch error. It would open up the other saves that I hadn't played just fine. 

Got to surfing around for the answer and it seems the most common fix was to be sure my software was up to date. Oh, well that must explain it I thought because 2013 was the last time I'd used it! Off I go and get a334c91but, this didn't fix anything. NOW it gives me this error when trying to load >any< of the save files.

---------------------------
Error
---------------------------
An exception was thrown (press Ctrl+C to copy):

System.MissingMethodException: Method not found: 'Gibbed.Borderlands2.FileFormats.Items.IPackableSlot Gibbed.Borderlands2.FileFormats.Items.PackedDataHelper`2.Decode(Byte[], Gibbed.Borderlands2.GameInfo.Platform)'.

   at Gibbed.Borderlands2.SaveEdit.BackpackViewModel.ImportData(WillowTwoPlayerSaveGame saveGame, Platform platform)

   at Gibbed.Borderlands2.SaveEdit.ShellViewModel.<>c__DisplayClass58_0.<ReadSave>b__2() in c:\projects\gibbed-borderlands2\projects\Gibbed.Borderlands2.SaveEdit\ShellViewModel.cs:line 356

   at Caliburn.Micro.Contrib.Results.DelegateResult.Execute(ActionExecutionContext context)
---------------------------
OK   
---------------------------

The editor is in a folder on the same drive as the installed game and the save files. Beyond this, I'm at a bit of a loss as to what to do. I'll try to also attach the save in question.

Thanks a bunch for any time you can spare!
[Save0007.zip](https://github.com/gibbed/Gibbed.Borderlands2/files/1613712/Save0007.zip)

**Comment by gibbed** [comment]
That error means you probably tried to overwrite an older save editor and didn't overwrite everything. I'd suggest deleting the save editor files and re-extracting it.

**Comment by Gotin-Drachenhart** [comment]
Ah that fixed it! Thanks a bunch man!
