### ISSUE TITLE
PLZ help,it really drives me nuts.Cuz can't load my saves

### ISSUE THREAD

**Issue by DrRichtohofen** [gibbed/Gibbed.Borderlands2#33]
---------------------------
Error
---------------------------
An exception was thrown (press Ctrl+C to copy):

System.InvalidOperationException: This implementation is not part of the Windows Platform FIPS validated cryptographic algorithms.

   at System.Security.Cryptography.SHA1Managed..ctor()

   at Gibbed.Borderlands2.FileFormats.SaveFile.Deserialize(Stream input, Platform platform, DeserializeSettings settings)

   at Gibbed.Borderlands2.SaveEdit.ShellViewModel.<>c__DisplayClass58_0.<ReadSave>b__2()

   at Caliburn.Micro.Contrib.Results.DelegateResult.Execute(ActionExecutionContext context)
---------------------------
确定   
---------------------------
every time I tried to load my saves it occurs .And I checked plenty of solutions none works.SO  really ,plz help me out with des one.

**Comment by DrRichtohofen** [comment]
![image](https://user-images.githubusercontent.com/35399372/34906496-b9c13b7c-f8a9-11e7-9330-a54aaba10d18.png)

**Comment by gibbed** [comment]
Please re-download the save editor and ensure that `Gibbed.Borderlands2.SaveEdit.exe.config` is extracted properly next to `Gibbed.Borderlands2.SaveEdit.exe`.

**Comment by DrRichtohofen** [comment]
![default](https://user-images.githubusercontent.com/35399372/34906739-1b5e1a72-f8ae-11e7-8a02-3c589344584a.png)

**Comment by DrRichtohofen** [comment]
did it again,I did even draged the stuff to the game root menu.STill...OMG.I reinstalled .NETframework.GEE.It's not workin.It must be something wrong.I just can't figure it out

**Comment by DrRichtohofen** [comment]
BTW I didn't find the exe.confid....in the folder.

**Comment by gibbed** [comment]
You downloaded the wrong archive, you want `saveedit-1.xx.zip`, not `borderlands2-1.xx.zip`. Though I'll put it on my TODO list to add the .config to end up in the `saveedit-1.xx.zip`.

**Comment by DrRichtohofen** [comment]
@gibbed SO I need to download a saveedit-1 zip?I'm not sure what I should do exactly.Does that mean that I can't simly edit my sav by using your tools only?right?Would be so kind as to give me a link to download it to fix des promlem.Thx

**Comment by DrRichtohofen** [comment]
Kinda confused here.

**Comment by DrRichtohofen** [comment]
Holy ...I get it.IT WORKS !!!!Thank you so much!!!!
