### ISSUE TITLE
Cant load save file

### ISSUE THREAD

**Issue by kingdru86** [gibbed/Gibbed.Borderlands2#34]
When i decrypt the file it works but when i go to load the save file that is decrypted the program crashes. But when i try and load the encrypted save file i get the invalid sha1 has which lets me know the program works, yet when trying to load a save it crashes. Mind you im on windows 10 so i have all requirements already.

Any idea on why it crashes from trying to load my save file?

**Comment by gibbed** [comment]
Not without proper information about how it's crashing. "It's crashing" doesn't tell me anything.

**Comment by xcier** [comment]
SHA1 means it in encrypted. 
You are probably using a very old save. I had this problem pulling saves from 2013 but it worked when I used older versions.
