### ISSUE TITLE
Named weapons bugged

### ISSUE THREAD

**Issue by BHAlucard** [gibbed/Gibbed.Borderlands2#35]
there are a number of weapons that when selected read the box out and refuses to allow to work the ophan maker is one of these items if you need a list of items that i have found i can provide it

**Comment by xcier** [comment]
Use this site
https://sparfires.imgur.com/

**Comment by gibbed** [comment]
Possibly fixed as of https://github.com/gibbed/Gibbed.Borderlands2/commit/844ce3427b877f8c8d032df1434fe9dd3edabe86.
