### ISSUE TITLE
I have a problem i can`t find a solution for anywhere online

### ISSUE THREAD

**Issue by schelias** [gibbed/Gibbed.Borderlands2#36]
When using gibbed, and I try to open an existing save file, I get a *reencode:missmatch* -error.
I have:
-the lates version of gibbed (a334c91 @ 11.11.2017 00:24)
-the latest version of bl2 (at standard of 14.02.2018)
-reinstalled .NETFramework 4
-set the correct platform(PC) in the open tab

You suggested including the save files to open in an earlier post I read here so here they are:
[BL2SaveFiles.zip](https://github.com/gibbed/Gibbed.Borderlands2/files/1723832/BL2SaveFiles.zip)
This is the save file I want to open, with the according .bak file that can be found in the saves folder as well

When creating a new save file from scratch, I can give weapons and shields, etc. in my inventory as normal, and when I save it with gibbed, close gibbed, open gibbed again, and try to open the newly created save file without playing it in BL2 before, it works.
But as soon as I open the save in the game and leave the game afterwards, i get the reencode:missmatch error.

I dont know if you have a solution to this problem, but it would be nice if anyone knew something.

Thx in advance.

**Comment by gibbed** [comment]
I need a copy of the save file that is giving you the reencode mismatch error.

If you're getting that with the ones you attached, then you're not using the latest BL2 save editor.

**Comment by schelias** [comment]
Can you give me informations on where gibbed needs to be installed(e.g. in the BL2 steamapps folder, etc...)
and give me a link and a discription of where i find the latest version?
Or you just attach the version you used on my files(i suppose you did try them successfully) here.
That would be great.

**Comment by gibbed** [comment]
https://github.com/gibbed/Gibbed.Borderlands2/releases

**Comment by GladLife** [comment]
Hey Gibbed, I'm having the exact same issue as Schelias described. 

I am not able to open any save files that have been played on in-game, but I am able to create new saves and modify them, and then play those saves within the game. As Schelias mentioned, I also have the latest version, have tried uninstalling and reinstalling, and have all the settings correct AFAIK.

Running windows 10, Using this save file. 



[Erroredsavs.zip](https://github.com/gibbed/Gibbed.Borderlands2/files/1730357/Erroredsavs.zip)

The 0002 profile was created using the editor, the 0001 was created in game. 

Thanks for your continued support of this tool! We appreciate it tons!

**Comment by GladLife** [comment]
Found a solution! I dont know how it works, but it does.

Delete all previous files relating to the save editor

Re-download the most recent commit called "borderlands2-1.0.5-with-symbols.zip"

Extract in your steamapps>common>BL2 folder

Within the bin folder that Gibbed installs, Right click the tool and run as administrator. These steps made both in game and save editor profiles readable again.

**Comment by schelias** [comment]
ok, that did work for me as well!
Thank you everybody!
