### ISSUE TITLE
Failed to load save: reencode mismatch 

### ISSUE THREAD

**Issue by Dankshire** [gibbed/Gibbed.Borderlands2#38]
I'm trying to edit some old characters and it won't let me use a character I've saved recently but the untouched characters from like 2015 are fine. I was reading and it said I needed the latest updated version of Gibbed along with the latest updated game. I couldn't find the updated gibbed. What should I do?

**Comment by gibbed** [comment]
https://github.com/gibbed/Gibbed.Borderlands2/releases

**Comment by Dankshire** [comment]
Thank you

**Comment by PaleRiderNZ** [comment]
I bought this recently and have all the dlc apart from the customisation packs for characters I don't use yet. I have gibbed 1.05 installed. I purchased the GOTY edition so did not need to get the season pass. Old saves which I get from the net open fine in gibbed but my own in game save gets the reencode mismatch error. Suggestions? Attached file if it helps
[Save0001.zip](https://github.com/gibbed/Gibbed.Borderlands2/files/1817624/Save0001.zip)

**Comment by CoaldustPony** [comment]
Just grabbed the latest build of this and also getting the reencode mismatch error when trying to load saves.

**Comment by dastar512** [comment]
I'm having the same problem. Downloaded most recent gibbed, and BL2 is up to date....so where am I going wrong? Help appreciated.

[save0009.zip](https://github.com/gibbed/Gibbed.Borderlands2/files/2056394/save0009.zip)

**Comment by Hakamaori** [comment]
I have the most up to date version of gibbed for all Borderlands and I have the most up to date version of the games themselves but I I am still getting the the reencode mismatch error when trying to load any of my characters.

**Comment by Hakamaori** [comment]
I was having issues with this until I completely deleted the folders for all of my Gibbed Borderlands folders, then reinstalled with with most current and up to date version. Now, they're all working great.
