### ISSUE TITLE
Crashing with PackedData

### ISSUE THREAD

**Issue by xcier** [gibbed/Gibbed.Borderlands2#40]
When creating hybrids via pending mission rewards gibbed crashes if you click on packed weapon/item rewards. 
Can you just fuse them together? From what i've looked at it just seems that the packed info is regarding quantity, item name, and slot that is equipped in. 
I accidentally click on this when trying to rush through projects.

**Comment by gibbed** [comment]
This doesn't appear to still be occurring, probably due to bumped WPF Toolkit version.
