### ISSUE TITLE
reencode mismatch

### ISSUE THREAD

**Issue by green-51** [gibbed/Gibbed.Borderlands2#41]
I know that people have brought up this issue in the past, and the issue seems to be fixed by downloading the latest version of the save editor, which I have done, so I have attached my save file in the hopes that someone can help me figure out what I'm doing wrong.
[Save0004.zip](https://github.com/gibbed/Gibbed.Borderlands2/files/1755212/Save0004.zip)

**Comment by gibbed** [comment]
Loads fine in the latest save editor.

https://github.com/gibbed/Gibbed.Borderlands2/releases
