### ISSUE TITLE
Adding skill points doesn't seem to work

### ISSUE THREAD

**Issue by 404UNFca** [gibbed/Gibbed.Borderlands2#44]
Not sure if I'm doing something wrong but I've edited General Skill Points to 200 and once ingame, my skill points remained the same as they were before the edit (68).

Tried using all 68 points, saving, then editing that save to 200 points. Stayed at 0.

**Comment by FromDarkHell** [comment]
The game removes all extra skill points.
If I'm level 72 (68 skill points), The game does the math for the points (72 - 4) and changes my points to that amount.
