### ISSUE TITLE
Golden Keys // Corrupt File

### ISSUE THREAD

**Issue by Leodarkw** [gibbed/Gibbed.Borderlands2#46]
Hey man, sorry to disturb you, I'm having an error inside the game when I edit the golden keys, I would like to have 250+ keys, or at least increase them, but every time I start the game it appears this "corrupt file" error and my keys go back to normal, but the rest of the edits seem to be normal !!, do you know any way to get more golden keys without shift codes ? By the way, you did a great job with the save edit !! xD love your work !

**Comment by gibbed** [comment]
The save editor doesn't allow you to edit golden keys. That is stored as part of your profile, not save files.

**Comment by DumbJoe** [comment]
ok so how would you edit the profile file then?
