### ISSUE TITLE
Reencode mismatch with community patch

### ISSUE THREAD

**Issue by steven0202** [gibbed/Gibbed.Borderlands2#47]
The neweset version of the community patch seems to have a reencode mismatch, if I try to load the save file. I dont know, maybe not an issue, if you don´t want to support the community patch, but I think a lot of people are using it.

**Comment by FromDarkHell** [comment]
https://github.com/gibbed/Gibbed.Borderlands2/releases

**Comment by gibbed** [comment]
I wouldn't mind creating a branch for the community patch if there is an actual issue. If after grabbing the latest release, you're still getting reencode mismatch, please provide some sample save files and I can take a look.

**Comment by MengusDew** [comment]
Getting the reenchode mismatch with the latest verion. I'm getting it with all my saves. here is one of them
[Save0001.zip](https://github.com/gibbed/Gibbed.Borderlands2/files/1865969/Save0001.zip)

**Comment by gibbed** [comment]
@MengusDew Your save sample loads fine in the latest build.

**Comment by MengusDew** [comment]
Ok. So If I do indeed have the latest version of the editor, and I still get this error message, yet you do not, even though we are using the exact same save file, then there obviously is something else awry. I noticed that I'm not the only one running into this situation. Maybe it has something to do with windows 10. I dun know.

**Comment by gibbed** [comment]
So when you're running the editor you see this title?

![gibbed s borderlands 2 save editor a334c91 10312017 624 pm](https://user-images.githubusercontent.com/85170/38881744-26c2f36e-422e-11e8-974c-10aa527546c6.png)
