### ISSUE TITLE
Troubling Saving PC file as 360 files

### ISSUE THREAD

**Issue by vinmyer13** [gibbed/Gibbed.Borderlands2#50]
I open up a PC file that I've downloaded and I'm trying to convert it to 360 using gibbed, so I switch the platform to 360 and save. Horizon keeps saying it's a wrong STFS package. Am I missing a step to convert the PC file to 360 using gibbed? Thanks in advance!

**Comment by ccfman2004** [comment]
Xbox 360 game saves are in a container package (CON file) which includes stuff like the save icons and title that you see on the dashboard.  Start a new game on the 360 and save it.  Then transfer the save to USB. You need to view the contents of the BL2 game save. Then you can right-click and inject the new .sav over the old file into the BL2 save container file and resign it.
