### ISSUE TITLE
xp not being added

### ISSUE THREAD

**Issue by NovaEB** [gibbed/Gibbed.Borderlands2#55]
I bumped up my Zero save a couple levels because I couldn't get past a mission, but now all XP I gain just... doesn't show?

**Comment by Njol** [comment]
In case anyone else has this issue: Click on "Sync" next to the XP field after changing the character's level to make the XP match the new level.
If you don't do this, you will still earn XP in game, but as the XP is less than what is required for the level of the character, you will first need to earn enough XP to legitimately gain the modded level before seeing any progress on the XP bar (and being able to earn new levels).
