### ISSUE TITLE
Renamed a save folder and don't know what to do

### ISSUE THREAD

**Issue by StewyTurtle** [gibbed/Gibbed.Borderlands2#57]
So i accidentally renamed one of my save folders for the Gib Save Editor. I haven't played Borderlands 2 in a while so i forgot changing the names of things screwed things in game over. I deleted Borderlands 2 to maybe get the regular folder back, but that didn't work. Is there any way for me to get my old save folder back or at least get a new one that links to my Borderlands account so i can just re-create my characters?

**Comment by gibbed** [comment]
That would depend on what you ended up renaming it to.

To my knowledge, the correct location for save files is:

`Documents\My Games\Borderlands 2\WillowGame\SaveData`
