### ISSUE TITLE
Alien Launchers disappear from inventory when loaded up. 

### ISSUE THREAD

**Issue by Yokrei** [gibbed/Gibbed.Borderlands2#59]
Using the gear calculator V2, making alien rocket launchers then putting them into your backpack makes them disappear when the game is loaded up.

**Comment by testcaoy7** [comment]
Some relics will be deleted by game as well.
For instance, Allegiance Relic.

**Comment by testcaoy7** [comment]
It appears that this repo has been abandoned.

**Comment by testcaoy7** [comment]
The BUG fix branch still not merged...

**Comment by diveyez** [comment]
... waiting on fix
