### ISSUE TITLE
Gibbed just exits.

### ISSUE THREAD

**Issue by spike512** [gibbed/Gibbed.Borderlands2#64]
Downloaded 1.0.5 save edit , opening the app works just fine , interacting with everything from "General" to "About" works alright but as soon as i place the mouse cursor on "New" or "Open" the app just exits, no popout message or anything.

**Comment by spike512** [comment]
Fixed it, just had to reinstall the .NET framework (I had the 4.5 version, installed the 4.7.2)

**Comment by Androxios** [comment]
I had this same problem for a while, but I realized that I wasn't selecting the PS3 in the drop-down box when selecting a file. It had upset me for some time, but I now realize that I'm an idiot. Don't make the same mistake guys.
