### ISSUE TITLE
Wont load saves

### ISSUE THREAD

**Issue by DhanyalFairley** [gibbed/Gibbed.Borderlands2#65]
Each time I try to load my Xbox 360 game saves I'm met with an error, it says I need to extract the save game with Modio or Equivalent. This error has only just started when I reset my PC. Any suggestions on how to fix this?

**Comment by LindBalls** [comment]
same here, it requested i extract using Modio, but even then it cant read the files anymore. Me thinks microsoft has made some mods to their game save format.

**Comment by jack22128** [comment]
I open my xbox 360 save and it pops up with an error saying "failed to load save: reencode mismatch" can you tell me how to fix this please

**Comment by gibbed** [comment]
@jack22128 
* Make sure you're using the correct save editor and latest version of the save editor.
* If you still have the issue, attach a copy of your save file here.
