### ISSUE TITLE
game crashes as soon as I load character. 

### ISSUE THREAD

**Issue by Reco3** [gibbed/Gibbed.Borderlands2#67]
I used bl2_all-tools_1.0.5-with-symbols, now every time I try to play the edited save on that character the game crashes.

**Comment by xcier** [comment]
What is your badass rank if it is above 4,294,967,295 because it is the max unsigned 32-bit integer

**Comment by Reco3** [comment]
No where close to that number. Although how where can I find out?

________________________________

**Comment by diveyez** [comment]
Reco, its in the mod options, just look.
He has a currpted save. He needs to learn to backup the file, then mod, and load. 
I had this happen, I couldnt restore it without a backup.
