### ISSUE TITLE
ps3 game save reencode mismatch.

### ISSUE THREAD

**Issue by hipvic18** [gibbed/Gibbed.Borderlands2#70]
so i just got in to borderlands 2  for the ps3 and theres a particular gun i like the maliwan alien railgun. im trying to use the save editor to make it my current level. i have everything updated but nothing works. i keep getting reencode mismatch. i have the game of the year edition and and not all the dlcs came with it i think that might be the issue im not sure and i used all my golden keys trying to get a new maliwan rail gun.
yes i stil play my ps3 lol black ops 1 still has an active comunity.

[BLUS30982-SAVE-SAVE0001.zip](https://github.com/gibbed/Gibbed.Borderlands2/files/2570107/BLUS30982-SAVE-SAVE0001.zip)

**Comment by Got-Spooked** [comment]
[Save0001.zip](https://github.com/gibbed/Gibbed.Borderlands2/files/3099253/Save0001.zip)

**Comment by gibbed** [comment]
This save opens fine in the latest version.
