### ISSUE TITLE
Windows 8.1 x64 App won't Open Due to a major dll file error

### ISSUE THREAD

**Issue by milldogtjm** [gibbed/Gibbed.Borderlands2#71]
The error that I get is this for Version 256; Also I gave it full admin rights, allowed through firewall as well, on a side note even tried the Windows compatibility mode 7 and 8 with no luck at all.
Source
Gibbed's Borderlands 2 Save Editor
Summary
Stopped working
Date
‎11/‎24/‎2018 7:58 PM
Status
Report sent
Description
Faulting Application Path:	C:\Program Files (x86)\Xbox360 Mod Programs\Borderlands series\Borderlnds 2 save editor ricks\Gibbed.Borderlands2.SaveEdit.exe
Problem signature
Problem Event Name:	APPCRASH
Application Name:	Gibbed.Borderlands2.SaveEdit.exe
Application Version:	1.0.0.0
Application Timestamp:	5634c163
Fault Module Name:	KERNELBASE.dll
Fault Module Version:	6.3.9600.19178
Fault Module Timestamp:	5bc006fd
Exception Code:	c06d007e
Exception Offset:	0000000000008e6c
OS Version:	6.3.9600.2.0.0.256.48
Locale ID:	1033
Additional Information 1:	ed02
Additional Information 2:	ed02a0aadfd0aa6c6cb5825519bfff96
Additional Information 3:	f43a
Additional Information 4:	f43aaaf2b3ac596c8a0868c2c9ea8647
Extra information about the problem
Bucket ID:	c5119f7cbfd8b5d84364821ba858b3d3 (1397384839691809747)

**Comment by gibbed** [comment]
This is likely to be a system issue and not a particular issue with the save editor.

**Comment by milldogtjm** [comment]
As an incompatibility for use on windows 8.1 x64 systems, also found out I get this also on windows 10 pro x64 with the latest updates sir.

**Comment by gibbed** [comment]
The save editor is not incompatible with Windows 8.1 x64 or Windows 10 x64, it's been used on both with no issues. Whatever problem, lies with your system.
