### ISSUE TITLE
Shotgun accessories are mismatched / do not spawn specified attachment

### ISSUE THREAD

**Issue by Soundwave2005** [gibbed/Gibbed.Borderlands2#73]
The Shotgun accessories are not spawning correctly. Specifying one attachment spawns a different attachment.

GD_Weap_Shotgun.Accessory.SG_Accessory_MoonClip spawns GD_Weap_Shotgun.Accessory.SG_Accessory_Tech_2

GD_Weap_Shotgun.Accessory.SG_Accessory_ShotgunShell spawns GD_Weap_Shotgun.Accessory.SG_Accessory_Tech_3

GD_Weap_Shotgun.Accessory.SG_Accessory_Tech_2 spawns GD_Weap_Shotgun.Accessory.SG_Accessory_Tech_4

GD_Weap_Shotgun.Accessory.SG_Accessory_Tech_3 spawns GD_Weap_Shotgun.Accessory.SG_Accessory_MoonClip

GD_Weap_Shotgun.Accessory.SG_Accessory_Tech_4 spawns GD_Weap_Shotgun.Accessory.SG_Accessory_ShotgunShell

GD_Weap_Shotgun.Accessory.SG_Accessory_Bayonet_3 and GD_Weap_Shotgun.Accessory.SG_Accessory_VerticalGrip have no issues.

**Comment by gibbed** [comment]
This is *probably* fixed in a hotfix to BL2. I never got around to looking at implementing hotfix changes in the editor.

**Comment by Soundwave2005** [comment]
You may want to take some time doing just that. It may also resolve the issue with the Ailen/E-tech Launchers not spawning at all. A hotfix may have moved some things around and "broken" the editor. Honestly, the Launchers should be a higher priority as the shotgun attachments at least still spawn.
