### ISSUE TITLE
does gibbed just not work anymore?

### ISSUE THREAD

**Issue by Crimsomreaf5555** [gibbed/Gibbed.Borderlands2#77]
when i edit a save like giving a weapon, giving money, iridium, skill points it just does not carry over into the game

**Comment by gibbed** [comment]
Then you are not updating your save properly, in whatever way. If you have the game running then try having the game not running when you make your save.

**Comment by Crimsomreaf5555** [comment]
or does gib just not premade saves like the ones from nexus i got some from here https://www.nexusmods.com/borderlands2/mods/14

**Comment by Crimsomreaf5555** [comment]
nope still dont work wether i have the game running or not

**Comment by Crimsomreaf5555** [comment]
[

](url)

**Comment by Crimsomreaf5555** [comment]
wow even editing the skill grade in raw does not work

**Comment by Crimsomreaf5555** [comment]
really think you should update this because nothing works

**Comment by gibbed** [comment]
It's not an issue with the editor, but your usage of it. Sorry, I don't know what your issue is.

**Comment by VerteDragonne** [comment]
This may be late on the reply, but my brother pointed out to me skill points dont work. Looking it up, i learned BL2 has sanity checks on skills. it checks skill points, skill levels, etc. If it sees something out of place, it resets you to a "proper" amount.

it's not that the editor doesn't work (technically, it does) it is simply the itself game keeps re-editing the save during load.
