### ISSUE TITLE
unable to load save files

### ISSUE THREAD

**Issue by dimetime35c** [gibbed/Gibbed.Borderlands2#8]
---------------------------
Error
---------------------------
An exception was thrown (press Ctrl+C to copy):

System.IO.FileLoadException: Could not load file or assembly 'protobuf-net, Version=2.0.0.580, Culture=neutral, PublicKeyToken=257b51d87d2e4d67' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

File name: 'protobuf-net, Version=2.0.0.580, Culture=neutral, PublicKeyToken=257b51d87d2e4d67'

   at Gibbed.Borderlands2.FileFormats.SaveFile.Deserialize(Stream input, Platform platform, DeserializeSettings settings)

   at Gibbed.Borderlands2.SaveEdit.ShellViewModel.<>c__DisplayClass29.<ReadSave>b__1e()

   at Caliburn.Micro.Contrib.Results.DelegateResult.Execute(ActionExecutionContext context)

WRN: Assembly binding logging is turned OFF.

To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.

Note: There is some performance penalty associated with assembly bind failure logging.

To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

thats what i get when i try and open any of my save files in gibbed. not sure if i need to update it or not. ive got the latest version from your other site and dont see anything to click to see if theres any updates

**Comment by gibbed** [comment]
You did not extract it properly or are missing files. For the old version on my site, there should be an `assemblies` directory next to `Gibbed.Borderlands2.SaveEdit.exe` with `protobuf-net.dll` in it.

**Comment by dimetime35c** [comment]
whats the latest version??? ive never used github and cant figure out where to find the download button for the installer

**Comment by dimetime35c** [comment]
never mind i got it working thanks for the quick reply and thanks for the help
