### ISSUE TITLE
BL2 why do i have to always start a new game

### ISSUE THREAD

**Issue by StedyNXS** [gibbed/Gibbed.Borderlands2#80]
why is it every time i make a character i have to start from the beginning? i usually just use this to get the weapons i want and put them on my main but i don't like having to get all the way to sanctuary every time

**Comment by ramnnv** [comment]
Probably because you're trying to get some dlc stuff and you dont have it installed.

**Comment by gibbed** [comment]
This shouldn't be happening unless you're creating a new save file and editing that.

If you're having this happen with an actual save file, please provide a sample of the unedited save file and the edited save file where this happens.

**Comment by StedyNXS** [comment]
i am unable to edit my own saves but i dowloaded a svae but anytime i add
something to it it restarts the game
