### ISSUE TITLE
Reencode Mismatch

### ISSUE THREAD

**Issue by Got-Spooked** [gibbed/Gibbed.Borderlands2#81]
I am using the latest version of Gibb, but I still get the reencode mismatch message whenever I attempt to open a save to edit it.
![OOF](https://user-images.githubusercontent.com/49794635/56439479-d7258200-62ab-11e9-89c2-b33ece910ceb.PNG)

**Comment by gibbed** [comment]
Attach your save file to this issue.

**Comment by Got-Spooked** [comment]
[Save0001.zip](https://github.com/gibbed/Gibbed.Borderlands2/files/3099257/Save0001.zip)

**Comment by gibbed** [comment]
Loads fine. Get [the latest release](https://github.com/gibbed/Gibbed.Borderlands2/releases/latest).

**Comment by Got-Spooked** [comment]
Sorry, I had downloaded the wrong file.
