### ISSUE TITLE
How bout be being less of a shitty project manager and provide build instructions. 

### ISSUE THREAD

**Issue by natedawg469** [gibbed/Gibbed.Borderlands2#83]
Since the file contains a .sln, I am assuming you build it in microsoft visual studio. 

"Typically each github project is provided with instructions to build/compile/run/use.

If you don't find that information, either the owner of that repository has a serious amnesia or it is not a well maintained project (Probably a good chance to start contributing to it by starting to add build/compile instructions)." Quoted from here: [https://www.quora.com/How-do-I-compile-and-run-github-projects](url)

**Comment by natedawg469** [comment]
Sorry I was being dumb. You provided the proper downloads link.

**Comment by gibbed** [comment]
There's a case to be made for me to finally put a proper README here, but throwing insults around is usually not the best way to ask.

Yes, you build with Visual Studio. I personally used Visual Studio 2010 at the time, but if I return to it I would probably migrate it to Visual Studio 2019. Any dependencies should automatically be picked up by NuGet.

[Release binaries are provided under the Releases section](https://github.com/gibbed/Gibbed.Borderlands2/releases). AppVeyor link is there but there's no guarantee that the artifacts from the automatic builds won't have expired by now.

**Comment by natedawg469** [comment]
Yeah, sorry. I was just misunderstanding that the download link provided from the blog already took us to the proper page for download. I was looking at this page for downloading: [https://github.com/gibbed/Gibbed.Borderlands2](url)

**Comment by natedawg469** [comment]
[https://github.com/gibbed/Gibbed.Borderlands2](url)
