### ISSUE TITLE
Failed to load save: reencode mismatch

### ISSUE THREAD

**Issue by daisukepr** [gibbed/Gibbed.Borderlands2#90]
I'm using 1.0.15 5/27/2019 9:53AM release along with Unofficial Community Patch and when I try to load my save it says "Failed to load save: reencode mismatch".

Save attached 
[Save0002.zip](https://github.com/gibbed/Gibbed.Borderlands2/files/3255509/Save0002.zip)

**Comment by gibbed** [comment]
Loads fine here.

**Comment by daisukepr** [comment]
How bizarre, it works with the redownloaded versions, but the one I already had still doesn't work.  Thank you for taking a look.
