### ISSUE TITLE
open ps4 file exported by save wizard 

### ISSUE THREAD

**Issue by startuga** [gibbed/Gibbed.Borderlands2#92]
[Save0001.zip](https://github.com/gibbed/Gibbed.Borderlands2/files/3259162/Save0001.zip)

**Comment by gibbed** [comment]
Sorry, I have plans to support a commercial save editor. Ask them to export/import the save file properly.

**Comment by Xeddius** [comment]
What is the Commercial Save Editor?

**Comment by gibbed** [comment]
@Xeddius Wow. I botched that originally, I meant "no plans". I'm not going to link any directly, would suggest Google.

**Comment by Xeddius** [comment]
@gibbed ah, it's all good. Thank you for making Gibbed, An ex of mine stole my PS3, Gibbed helped me recover the save from my backed-up ps3 saves and I was able convert it to Xbox360 and PC format.

@startuga If it's still supported and you have a ps3 you should upload your save to the cloud from the main menu on ps4, download to the ps3, backup your save files to usb/flashdrive, plug in to pc, Decrypt the save with ps3 bruteforce save data, and then open it with Gibbed, make the changes you need/want, save the file (Be sure it's set to ps3), re-encrypt, copy back to usb, copy back to ps3, upload the character to the cloud again, download on ps4, and enjoy. (There is a small bug where badass points/tokens get duplicated in this process. pretty interesting.)
