### ISSUE TITLE
Fire Drill pistol from the Commander Lilith DLC has incorrect body in Gibbed.

### ISSUE THREAD

**Issue by Aaron00000** [gibbed/Gibbed.Borderlands2#95]
It is currently listed as having "Anemone Body 5" in gibbed when in actuality it spawn with "Anemone Body 4" in-game. Fire Drills get deleted if you try to gib them in currently.

**Comment by gibbed** [comment]
You're going to have to give me exact paths here. I'd rather not be searching for what you mean by "Anomone Body 5"/"Anemone Body 4". Just copy past the values from the editor.

**Comment by FromDarkHell** [comment]
The body of the Fire Drill shown in Gibbed is, `GD_Anemone_Weapons.Body.Pistol_Body_Vladof_5` while in game the body should be, `GD_Anemone_Weapons.Body.Pistol_Body_Vladof_4` meaning that all Gibbed Fire Drills will be deleted via sanity check.
