### ISSUE TITLE
Cannot start the program.

### ISSUE THREAD

**Issue by Pellsyboi** [gibbed/Gibbed.Borderlands2#97]
With the release of the Commander Lilith DLC, I cannot find the .exe file to run the program, is there something obvious I'm missing?

**Comment by gibbed** [comment]
You didn't download the correct thing.

https://github.com/gibbed/Gibbed.Borderlands2/releases/latest

**Comment by Pellsyboi** [comment]
My bad, you were right... I'm stupid, thanks a bunch, and love your work!
